<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Web Paint Application</title>

    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <link rel="stylesheet" type="text/css" href="/css/web-paint.css" />
</head>
<body>
    
    <!-- Navbar start -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Web Paint</a>
            </div>
            
            <!-- MainMenu start -->
            <dvi class="collapse navbar-collapse" id="main-navigation">
                <?php if ($this->authentication()->hasIdentity()): ?>
                <ul class="nav navbar-nav">
                    <li><a href="/paint">Paint</a></li>
                </ul>
                <?php endif; ?>
                
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                    
                        <ul class="dropdown-menu">
                            <?php if ($this->authentication()->hasIdentity()) { ?>
                            <li class="disabled"><a href="">Signed as <b><?php echo $this->authentication()->getIdentity()->username; ?></b></a></li>
                            <li class="divider"></li>
                            <li><a href="/signout">Signout</a></li>
                            <?php } else { ?>
                            <li><a href="/signin">Signin</a></li>
                            <li><a href="/signup">Signup</a></li>
                            <?php } ?>
                        </ul>
                    </li>
                </ul>
            </dvi>
            <!-- MainMenu end -->
            
        </div>
    </nav>
    <!-- Navbar end -->

    <!-- Content start -->
    <div class="container">
    <?php echo isset($content) ? $content : ''; ?>
        <hr />
        <footer>
            &copy;2014
        </footer>
    </div>
    <!-- Content end -->
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <script type="text/javascript" src="/js/web-paint.js"></script>
</body>
</html>