<div id="paint-menu">
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            File <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li id="paint-file-new"><a href="#">New</a></li>
            <li id="paint-file-open"><a href="#">Open</a></li>
            <li id="paint-file-save"><a href="#">Save</a></li>
            <li class="divider"></li>
            <li id="paint-file-exit"><a href="/signout">Exit</a></li>
        </ul>
    </div>
    
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span id="paint-instrument-current">Instrument</span> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li id="paint-instrument-brush"><a href="#">Brush</a></li>
            <li id="paint-instrument-line"><a href="#">Line</a></li>
            <li id="paint-instrument-rectangle"><a href="#">Rectangle</a></li>
        </ul>
    </div>
    
    <input type="color" id="paint-color-bg" value="#000000" />
    <input type="color" id="paint-color-fg" value="#ffffff" />
    
    <select id="paint-rectangle-type">
        <option value="rect">Fill and stroke</option>
        <option value="fill">Fill rectangle</option>
        <option value="stroke">Stroke rectangle</option>
    </select>
    
    <select id="paint-line-width">
        <option value="1">1 px</option>
        <option value="3">3 px</option>
        <option value="5">5 px</option>
        <option value="10">10 px</option>
        <option value="15">15 px</option>
        <option value="20">20 px</option>
    </select>
    
    <select id="paint-line-cap">
        <option value="butt">Butt</option>
        <option value="round">Round</option>
        <option value="square">Square</option>
    </select>
    
</div>

<div>
    <canvas id="paint" width="800" height="600">
        Your borwser is not support HTML5 &gt;canvas&lt; element
    </canvas>
</div>